### ISSUE TITLE
Zon package manager support

### ISSUE THREAD

**Issue by nilslice** [extism/zig-pdk#18]
I'm still learning about this, but it seems there is a way to more reliably distribute Zig libraries, e.g. https://github.com/hexops/mach/blob/main/build.zig.zon

Tracking this as something we should look into, not necessarily for v1.0 beta.

**Comment by usdogu** [comment]
We're already using the Zig package system since #8, but it now requires us to provide a paths argument in the zon file (ziglang/zig#17392). I'll implement a quick PR to fix this
