### ISSUE TITLE
Publish to astrolabe.pm & aquila.red registries

### ISSUE THREAD

**Issue by nilslice** [extism/zig-pdk#3]
Will need to register with https://astrolabe.pm/

Follow directions on https://github.com/mattnite/gyro#publishing-a-package-to-astrolabepm + setup a release Action workflow.

**Comment by usdogu** [comment]
Would be better to also publish to https://aquila.red/

**Comment by nilslice** [comment]
Ok, noted! Will also do that. Thank you

**Comment by usdogu** [comment]
Closing this since we don't have support for gyro/zigmod anymore
