### ISSUE TITLE
quality of life improvements

### ISSUE THREAD

**Issue by nilslice** [extism/zig-pdk#32]
1. errors
error formatting could be improved vs. setting a `[]const u8`.. more like https://github.com/ziglang/zig/blob/master/lib/std/fmt.zig#L83

e.g.

```zig
try plugin.allocError("some error {s}", .{ err });
```
(this probably applies generally, wherever we take []const u8 for things to signal info back to the host.. e.g. logging perhaps)

2. use new std HTTP types
such as the HTTP methods and other items where possible

thank you to @ethanholz for the inspiration and user report on Twitch! (https://www.twitch.tv/ninja_tron)

3. make `LogLevel` public
then its more flexible to write wrapper logging functions

**Comment by nilslice** [comment]
Sorry this took so long to get around to! But there's a PR open at #38

**Comment by ethanholz** [comment]
These looks cool! Great work!
